[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "*"
# image = { version = "*", features = ["png"], default-features = false }
libloader = "*"
sfml = "*"
signals = { path = "../signals" }
